simplesocial/groups/urls.py
# from django.conf.urls import url

# from . import views

# app_name = 'groups'

# urlpatterns = [
#     url(r"^$", views.ListGroups.as_view(), name="all"),
#     url(r"^new/$", views.CreateGroup.as_view(), name="create"),
#     url(r"^posts/in/(?P<slug>[-\w]+)/$",
#         views.SingleGroup.as_view(), name="single"),
#     url(r"join/(?P<slug>[-\w]+)/$", views.JoinGroup.as_view(), name="join"),
#     url(r"leave/(?P<slug>[-\w]+)/$", views.LeaveGroup.as_view(), name="leave"),
# ]


from django.urls import path
from . import views
app_name = "groups"

urlpatterns = [
    path("", views.ListGroup.as_view(), name='list_group'),
    path("new", views.CreateGroup.as_view(), name="create_group"),
    path("detail/<slug:slug>", views.DetailGrop.as_view(), name='detail'),
    path("join/<slug:slug>", views.join_group, name='join'),
    path("leave/<slug:slug>", views.leave_group, name='leave'),


]

simplesocial/posts/urls.py
from django.urls import path
from . import views
app_name = "posts"

urlpatterns = [
    path('', views.get_post_of_user, name="get_post_of_user"),
    path('new/', views.CreatePostView.as_view(), name="create_post"),

]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('groups/', include('groups.urls', namespace="groups")),
    path('posts/', include('posts.urls', namespace="posts")),
    path('', views.HomePage, name="home"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplesocial/groups/models.py
from django.db import models
# for slug
# you can use this to make slug without any hassle
from django.utils.text import slugify
import misaka
# MISAKA IS THE PACKAGE THAT ALLOWES US TO
# MWRITE MARKDOWN INSIDE THE FORMS AND USING MODELS
# when you post something with misaka you can post link markdown
# without any problem
from django.urls import reverse
from django.contrib.auth.models import User
# now we import another package that will
# allow us to use custom tags in the template for better use
# you can register you own tag
from django import template
register = template.Library()


# class Group(models.Model):
#     name = models.CharField(max_length=255, unique=True)
#     slug = models.SlugField(allow_unicode=True, unique=True)
#     description = models.TextField(blank=True, default='')
#     description_html = models.TextField(editable=False, default='', blank=True)
#     members = models.ManyToManyField(User,through="GroupMember")


class Group(models.Model):
    name = models.CharField(max_length=100, unique=True)

    # every time we have to use the primary key
    # insted we are going to use the slug
    # this is the new style
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    # ONE USER CAN BE A MEMBER OF MULTIPLE GROUP
    #  ONE GROUP CAN HAVE MULTIPLE USER
    #  SO ITS A MANY TO MANY RELATIONSHIP
    # and when you make a many to many relationship
    # you need to probide a pivot table with the through="" option
    # to store this information and and connected this two table
    # in many to many way
    # but remember if you dont do that no problem django will
    # automatically create one in the back end
    # in django you dont need to worry about Many to Many relation
    # like the other framework
    members = models.ManyToManyField(User, through="GroupMembers")


# Provide a many-to-many relation by using an intermediary model that
# holds two ForeignKey fields pointed at the two sides of the relation.

# Unless a through model was provided, ManyToManyField will use the
# create_many_to_many_intermediary_model factory to automatically generate the intermediary model.
    # we overrite some method


    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        # slugfy the slug field
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)

        return super().save(*args, **kwargs)

    # after a successfull post in the model
    # where would you go

    class Meta:
        ordering = ['name']

    def get_absolute_url(self):
        return reverse('groups:detail', kwargs={'slug': self.slug})


class GroupMembers(models.Model):
    # a group member consists of the group and its user
    # to how which group is related with which group
    # consider this as a pivot table for the many to many relationship
    group = models.ForeignKey(
        Group, related_name='membership', on_delete=models.CASCADE)
    user = models.ForeignKey(
        User, related_name='user_groups', on_delete=models.CASCADE)

simplesocial/groups/views.py
from django.shortcuts import render
# mixins are used as a decorator like in function view
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse
from django.views import generic
from .models import Group, GroupMembers
from django.contrib.auth.decorators import login_required
from .models import Group
from django.shortcuts import get_object_or_404, redirect


# tmp
from django.http import HttpResponse

# we create a class based CRUD
# login required mixin is substitute for login required


class CreateGroup(LoginRequiredMixin, generic.CreateView):
    fields = ('name', 'description')
    model = Group

# detail of the group
# you dont need permission for watching  a group details


class DetailGrop(generic.DetailView):
    model = Group


class ListGroup(generic.ListView):
    model = Group


@login_required
def join_group(request, slug):
    group = get_object_or_404(Group, slug=slug)
    group.members.add(request.user)
    group.save()
    return redirect('groups:list_group')


@login_required
def leave_group(request, slug):
    group = get_object_or_404(Group, slug=slug)
    if request.user in group.members.all():
        group.members.remove(request.user)
        return redirect('groups:list_group')

simplesocial/templates/groups/group_detail.html
{% extends "base.html" %} {% block content %}

<div class="jumbotron jumbotron-fluid">
  <h1 class="display-4 techfont">{{group.name}}</h1>
  <hr />
  <p class="techfont">{{group.description}}</p>

  <center>
    <button class="btn btn-warning btn-lg techfont">All Comments</button>
  </center>

  <ul class="techfont">
    {% for post in group.posts.all %}
    <div class="btn btn-warning">from @{{post.user}}</div>
    <small class=""> posted at {{post.created_at}}</small>

    <li class="jumbotron">{{post.message}}</li>
    <hr />
    {% endfor %}
  </ul>
</div>

{% endblock %}

simplesocial/templates/groups/group_form.html
{% extends 'base.html' %} {% load crispy_forms_tags %} {% block title %} Login
{% endblock title %} {% load static %} {% block content %}

<h2>Create Group</h2>
<div class="jumbotron jumbotron-fluid">
  <div class="form-group">
    <form method="POST">
      {% csrf_token %} {{form|crispy}}
      <input
        type="submit"
        class="btn btn-warning btn-lg"
        value="Create Group"
      />
    </form>
  </div>
</div>
{% endblock %}

simplesocial/templates/groups/group_list.html
{% extends "base.html" %} {% block content %}

<div class="jumbotron jumbotron-fluid">
  {% for group in object_list %}
  <a href="{% url 'groups:detail' slug=group.slug %}">
    <h2 class="display-4 techfont">
      {{group.name}} <small> [ {{group.members.count}} ]</small>
    </h2>
  </a>
  {% if user in group.members.all %}
  <a href="{% url 'groups:leave' group.slug %}"
    ><button class="btn btn-danger techfont">Leave Group</button>
  </a>
  {% else %}
  <a href="{% url 'groups:join' group.slug %}"
    ><button class="btn btn-danger techfont">Join Group</button>
  </a>
  {% endif %} {% endfor %}
</div>

{% endblock %}