simplesocial/accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'

urlpatterns = [
    # if you give the name just login in the name=
    # some additional benigfits you have
    # like login redirect
    path("login/", views.login_user, name='login'),
    path("logout/", views.logout_user, name="logout"),
    path("signup/", views.signup_user, name="signup"),
]

simplesocial/groups/urls.py
# from django.conf.urls import url

# from . import views

# app_name = 'groups'

# urlpatterns = [
#     url(r"^$", views.ListGroups.as_view(), name="all"),
#     url(r"^new/$", views.CreateGroup.as_view(), name="create"),
#     url(r"^posts/in/(?P<slug>[-\w]+)/$",
#         views.SingleGroup.as_view(), name="single"),
#     url(r"join/(?P<slug>[-\w]+)/$", views.JoinGroup.as_view(), name="join"),
#     url(r"leave/(?P<slug>[-\w]+)/$", views.LeaveGroup.as_view(), name="leave"),
# ]


from django.urls import path
from . import views
app_name = "groups"

urlpatterns = [
    path("", views.ListGroup.as_view(), name='list_group'),
    path("new", views.CreateGroup.as_view(), name="create_group"),
    path("detail/<slug:slug>", views.DetailGrop.as_view(), name='detail'),
    path("join/<slug:slug>", views.join_group, name='join'),
    path("leave/<slug:slug>", views.leave_group, name='leave'),


]

simplesocial/posts/urls.py
from django.urls import path
from . import views
app_name = "posts"

urlpatterns = [
    path('', views.get_post_of_user, name="get_post_of_user"),
    path('new/', views.CreatePostView.as_view(), name="create_post"),

]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('groups/', include('groups.urls', namespace="groups")),
    path('posts/', include('posts.urls', namespace="posts")),
    path('', views.HomePage, name="home"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplesocial/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <title>Social Hub</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="shortcut icon" href="https://di.phncdn.com/www-static/favicon.ico?cache=2020071602" />
    <link rel="alternate" type="application/rss+xml" title="PornHub - RSS Feed" href="/rss" />

    <link rel="stylesheet" href="https://di.phncdn.com/www-static/css/generated-header.css?cache=2020071602"
        type="text/css" />
   <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
      crossorigin="anonymous"
    />

    <!-- Optional theme -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
    />

    {# MEDIUM STYLE EDITOR#}
    <script src="//cdn.jsdelivr.net/medium-editor/latest/js/medium-editor.min.js"></script>
    <link
      rel="stylesheet"
      href="//cdn.jsdelivr.net/medium-editor/latest/css/medium-editor.min.css"
      type="text/css"
      media="screen"
      charset="utf-8"
    />
    <script
      src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js"
      referrerpolicy="origin"
    ></script>

    {# Custom CSS#}
    <link rel="stylesheet" href="{% static 'css/blog.css' %}" />
    
    {# Fonts#}
    <link
      href="https://fonts.googleapis.com/css?family=Montserrat|Russo+One"
      rel="stylesheet"
    />
  </head>

  <body class="loader">
    <style>
        body {
            background-color: black;
        }
    </style>
      
      
<nav class="navbar  techfont" role="navigation" id="navbar">
    
        <img src="{% static 'images/logo.png' %}" alt="" style="height: 300px; width: 100%">
    
    
    <div class="container">
        
        
        <a class="navbar-brand mynav" href="{% url 'home' %}">Social Hub</a>

        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li class="btn btn-danger btn-lg">Welcome @{{request.user}}</li>
            <li><a href="{% url 'posts:create_post' %}" class="btn btn-simple"> Create Post</a></li>
            <li><a href="{% url 'posts:get_post_of_user' %}" class="btn btn-simple"> Your Posts</a></li>

            <li><a href="{% url 'groups:list_group' %}" class="btn btn-simple">Groups</a></li>
            <li><a href="{% url 'groups:create_group'%}" class="btn btn-simple">Create Group</a></li>
            <li><a  class="btn btn-simple" href="{% url 'accounts:logout' %}">Log out</a></li>
            
            {% else %}
            <li><a href="{% url 'groups:list_group' %}" class="btn btn-simple">Groups</a></li>
            <li><a  class="btn btn-simple" href="{% url 'accounts:login' %}">Log in</a></li>
            <li><a  class="btn btn-simple" href="{% url 'accounts:signup' %}">Sign up</a></li>
            {% endif %}
        </ul>



    </div>
</nav>
<div class="container mycontent">
    {% block content %}

    {% endblock %}

</div>



<canvas id="canvas"></canvas>



</body>
<script src="{% static "simplesocial/js/master.js"%}" type="text/javascript"></script>

</html>

simplesocial/templates/index.html
{% extends "base.html" %} {% block content%} {% endblock %}